# Linear Algebra for CpE

## Laboratory 7 : Matrix Operations

### Activity

### Task 1 

Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$. In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [1]:
import numpy as np 
import matplotlib.pyplot as plt 
%matplotlib inline 

In [56]:
A = np.array([[2 ,2, 4],[5, -3, 4],[0, -2, 3]])
B = np.array([[1 ,2, 5],[5, -1, 0],[0, -3, 3]])
C = np.array([[3 ,2, 5],[3, 7, 5],[2, -3, -3]])

1. $A \cdot B \neq B \cdot A$

In [57]:
A.dot(B)

array([[ 12, -10,  22],
       [-10,   1,  37],
       [-10,  -7,   9]])

In [58]:
B.dot(A)

array([[ 12, -14,  27],
       [  5,  13,  16],
       [-15,   3,  -3]])

In [59]:
np.array_equiv(A.dot(B), B.dot(A))

False

2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$

In [60]:
A.dot(B.dot(C))

array([[  50, -112,  -56],
       [  47, -124, -156],
       [ -33,  -96, -112]])

In [61]:
(A.dot(B)).dot(C)

array([[  50, -112,  -56],
       [  47, -124, -156],
       [ -33,  -96, -112]])

In [62]:
np.array_equiv(A.dot(B.dot(C)), (A.dot(B).dot(C)))

True

3. $A\cdot(B+C) = A\cdot B + A\cdot C$

In [63]:
A.dot(B+C)

array([[ 32,  -4,  30],
       [  4, -22,  35],
       [-10, -30, -10]])

In [64]:
A.dot(B)+A.dot(C)

array([[ 32,  -4,  30],
       [  4, -22,  35],
       [-10, -30, -10]])

In [65]:
np.array_equiv(A.dot(B+C), A.dot(B)+A.dot(C))

True

4. $(B+C)\cdot A = B\cdot A + C\cdot A$

In [66]:
(B+C).dot(A)

array([[ 28, -24,  62],
       [ 46, -12,  71],
       [-26,  22, -16]])

In [67]:
B.dot(A)+C.dot(A)

array([[ 28, -24,  62],
       [ 46, -12,  71],
       [-26,  22, -16]])

In [68]:
np.array_equiv((B+C).dot(A), B.dot(A)+C.dot(A))

True

5. $A\cdot I = A$

In [69]:
I = np.array(A.dot(np.linalg.inv(A)), dtype=int)
I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [70]:
A.dot(I)

array([[ 2,  2,  4],
       [ 5, -3,  4],
       [ 0, -2,  3]])

In [71]:
A

array([[ 2,  2,  4],
       [ 5, -3,  4],
       [ 0, -2,  3]])

In [72]:
np.array_equiv(A.dot(I), A)

True

6. $A\cdot \emptyset = \emptyset$

In [73]:
A.dot(np.zeros(A.shape))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [74]:
np.zeros(A.shape)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [75]:
np.array_equiv(A.dot(np.zeros(A.shape)), np.zeros(A.shape))

True